### ISSUE TITLE
I have a question about evalation

### ISSUE THREAD

**Issue by sonder-tutu** [aswahd/SamRadiology#2]
I just had a read to your codebase.Very neat work!
I have a question about evalation as the following:
`Traceback (most recent call last):
  File "/home/dell/lixue/Programs/SamRadiology-main/SamRadiology-main/sam2rad/evaluation/eval_bounding_box.py", line 235, in <module>
    evaluator.eval(tst_dl)
  File "/home/dell/anaconda3/envs/sam2rad_lx/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/dell/lixue/Programs/SamRadiology-main/SamRadiology-main/sam2rad/evaluation/eval_bounding_box.py", line 186, in eval
    self.eval_batch(batch)
  File "/home/dell/lixue/Programs/SamRadiology-main/SamRadiology-main/sam2rad/evaluation/eval_bounding_box.py", line 141, in eval_batch
    raise ValueError(f"Invalid input_size or original_size. input_size: {input_size}, original_size: {original_size}")
ValueError: Invalid input_size or original_size. input_size: [tensor([1024]), tensor([1024])], original_size: [212]`

**Comment by aswahd** [comment]
@sonder-tutu 

It's fixed now. Please pull the latest commit.

thanks.
